package com.neusoftwjj.crm.settings.mapper;


import com.neusoftwjj.crm.settings.model.DicType;

import java.util.List;

public interface DicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Tue Nov 15 10:29:16 CST 2022
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Tue Nov 15 10:29:16 CST 2022
     */
    int insert(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Tue Nov 15 10:29:16 CST 2022
     */
    int insertSelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Tue Nov 15 10:29:16 CST 2022
     */
    DicType selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Tue Nov 15 10:29:16 CST 2022
     */
    int updateByPrimaryKeySelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Tue Nov 15 10:29:16 CST 2022
     */
    int updateByPrimaryKey(DicType record);
    /**
     * 查询所有字典类型
     */
    List<DicType> selectAllDicType();
    /**
     * 添加字典类型
     */
    int insertDicType(DicType dicType);
    /**
     * 根据编码查询字典类型
     */
    DicType selectDicTypeByCode(String code);
    /**
     * 根据编码修改字典类型
     */
    int updateDicTypeByCode(DicType dicType);
    /**
     * 根据多个编码删除字典类型
     */
    int deleteDicType(String[] codes);
}