package com.neusoftwjj.crm.settings.mapper;


import com.neusoftwjj.crm.settings.model.DicValue;

import java.util.List;

public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Sep 10 15:54:37 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Sep 10 15:54:37 CST 2022
     */
    int insert(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Sep 10 15:54:37 CST 2022
     */
    int insertSelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Sep 10 15:54:37 CST 2022
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Sep 10 15:54:37 CST 2022
     */
    int updateByPrimaryKeySelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Sep 10 15:54:37 CST 2022
     */
    int updateByPrimaryKey(DicValue record);
    /**
     *根据typeCode查询数据字典值
     */
    List<DicValue> selectDicValueByTypeCode(String typeCode);
    /**
     * 联合数据字典类型查询所有字典值
     */
    List<DicValue> selectAllDicValue();
    /**
     * 添加数据字典值
     */
    int insertDicValue(DicValue dicValue);
    /**
     * 根据id查询数据字典值
     */
    DicValue selectDicValueById(String id);
    /**
     * 根据id更新字典值
     */
    int updateDicValueById(DicValue dicValue);
    /**
     * 根据ids删除字典值
     */
    int deleteDicValueByIds(String[] ids);
}